### ISSUE TITLE
Investigate the bmctl k8s cluster creating on ABM takes which is slow and takes ~15mins for 2 node cluster

### ISSUE THREAD

**Issue by puneith** [GoogleCloudPlatform/anthos-samples#15] opened 2021-04-21 13:42 UTC
Once the Terraform ABM (GCE instances) are provisioned, the following setup takes a long time (~15mins) even for a 2 node cluster

```
sudo ./preflights.sh && \
  sudo bmctl create config -c anthos-gce-cluster && \
  sudo cp ~/anthos-gce-cluster.yaml bmctl-workspace/anthos-gce-cluster && \
  sudo bmctl create cluster -c anthos-gce-cluster
```

Investigate the reasons for slow cluster creation.

**Comment by Shabirmean** [comment] 2021-11-07 01:15
The installation process usually involves:
- Creating a temporary bootstrap cluster
- Configuring the nodes of the cluster with an ansible runner
- Doing preflight checks on each of the nodes and validating the network and readiness status
- Connecting to GCP with GKE Connect
- Deleting the temporary bootstrap cluster

Generally the installation process can take up to 15-20 minutes even for 2 node clusters. For example [this sample](https://github.com/GoogleCloudPlatform/anthos-samples/blob/master/anthos-bm-openstack-terraform/docs/install_abm.md#23-create-the-anthos-on-bare-metal-cluster) for installing a 2 node cluster in OpenStack takes up to 15-20 minutes. 

In cases where it takes longer and seems there is no-progress, the best approach is use the temporarily created `kind` cluster to see what is happening with the creation process and see if something is stuck. This document [can be followed ](https://cloud.google.com/anthos/clusters/docs/bare-metal/latest/troubleshooting/create-upgrade) to help with the `kind cluster debug process`. 

Sometimes, it could be because of a network issue as well. In such cases it is essential to look at a snapshot of the cluster to be able to exactly identify where the issue is. [This guide](https://cloud.google.com/anthos/clusters/docs/bare-metal/latest/troubleshooting/bmctl-snapshot) explains how to get a snapshot of the cluster state to further investigate issues. 

Closing this issue, since partially it is expected behaviour and partially, we need further information about the environment to be able to reproduce/dig deeper into the root cause.

**Closed by Shabirmean** 2021-11-07 01:15 UTC
Labels: type: feature request, priority: p2, samples
